// "use client"
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Image from "next/image"
import SliderContent from "@/components/SliderContent";
// import LogoCarousel from "@/components/S";

// import sliderimg01 from "/assets/images/slider-img01.png";
// import sliderimg02 from "/assets/images/slider-img02.png";



import Carousel from "@/components/S";
import Quality from "@/components/Quality";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Segenet Beauty & Spa",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">

  
<body className={inter.className}>
<NavBar/>   
{/* <LogoCarousel/> */}

 <Carousel/>
<Quality/>


{/* <SliderContent/>  */}
  {children
  }
  <Footer/>
  </body>
    </html>
  );
}
